from processor.comparison.interpreter import Comparator

def test_comparator():
    comparator = Comparator('0.1', {'a': 'b'}, 'a', 'exist')
    print(type(comparator))
    comparator = Comparator('0.2', {'a': 'b'}, 'a', 'exist')
    print(comparator.validate())
    print(type(comparator))
    comparator = Comparator('0.3', {'a': 'b'}, 'a', 'exist')
    print(type(comparator))
    print(type(comparator.comparator))
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b'}, 'b', 'exist')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b'}, 'b', 'not exist')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 1}}, 'c.e', 'not exist')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 1}}, 'c.d', 'not exist')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 1}}, 'c.d', 'exist')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 10}}, 'c.d', 'gt 10')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 10}}, 'c.d', 'eq 10')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 10}}, 'c.d', 'neq 5')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'eq "eastus"')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'eq len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'neq len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'gt len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'gte len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'lt len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', 'lte len(7)')
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 'eastus2'}}, 'c.d', "eq '{2}.location'")
    print(comparator.validate())
    comparator = Comparator('0.1', {'a': 'b', 'c': {'d': 10}}, 'c.d', 'gtw 10')
    print(comparator.validate())